keys:
  - &atelier age158hl482xhjnn9zx0vnj4nx3mq6rz0nvt3ktrserxv64zcglxkqdqaczdng
  - &ally age1xxdeydchzzl8vqf6yj4xnz7kqfqrlhyayv0kp7653upgtkr55assk5z7jz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *atelier
      - *ally
